# This is a basic workflow to help you get started with Actions

name: UpdateDataSources

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # CRON schedule at 2am UTC (10PM EDT)
  schedule:
    - cron: '0 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "data-update"
  data-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
      - name: install-dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: fetch-data
        run: python ../../app/get_vaccination_data.py

      - name: update-data
      - uses: test-room-7/action-update-file@v1
        with:
          file-path: ../../data/us_state_vaccinations.csv
          commit-msg: Automatically update us_state_vaccinations.csv
          github-token: ${{ secrets.GITHUB_TOKEN }}
